<template>
  <div id="Profile">
    <scroll class="content">
      <ul>
        <li>listdatas1</li>
        <li>listdatas2</li>
        <li>listdatas3</li>
        <li>listdatas4</li>
        <li>listdatas5</li>
        <li>listdatas6</li>
        <li>listdatas7</li>
        <li>listdatas8</li>
        <li>listdatas9</li>
        <li>listdatas10</li>
        <li>listdatas11</li>
        <li>listdatas12</li>
        <li>listdatas13</li>
        <li>listdatas14</li>
        <li>listdatas15</li>
        <li>listdatas16</li>
        <li>listdatas17</li>
        <li>listdatas18</li>
        <li>listdatas19</li>
        <li>listdatas20</li>
        <li>listdatas21</li>
        <li>listdatas22</li>
        <li>listdatas23</li>
        <li>listdatas24</li>
        <li>listdatas25</li>
        <li>listdatas26</li>
        <li>listdatas27</li>
        <li>listdatas28</li>
        <li>listdatas29</li>
        <li>listdatas30</li>
        <li>listdatas31</li>
        <li>listdatas32</li>
        <li>listdatas33</li>
        <li>listdatas34</li>
        <li>listdatas35</li>
        <li>listdatas36</li>
        <li>listdatas37</li>
        <li>listdatas38</li>
        <li>listdatas39</li>
        <li>listdatas40</li>
        <li>listdatas41</li>
        <li>listdatas42</li>
        <li>listdatas43</li>
        <li>listdatas44</li>
        <li>listdatas45</li>
        <li>listdatas46</li>
        <li>listdatas47</li>
        <li>listdatas48</li>
        <li>listdatas49</li>
        <li>listdatas50</li>
        <li>listdatas51</li>
        <li>listdatas52</li>
        <li>listdatas53</li>
        <li>listdatas54</li>
        <li>listdatas55</li>
        <li>listdatas56</li>
        <li>listdatas57</li>
        <li>listdatas58</li>
        <li>listdatas59</li>
        <li>listdatas60</li>
        <li>listdatas61</li>
        <li>listdatas62</li>
        <li>listdatas63</li>
        <li>listdatas64</li>
        <li>listdatas65</li>
        <li>listdatas66</li>
        <li>listdatas67</li>
        <li>listdatas68</li>
        <li>listdatas69</li>
        <li>listdatas70</li>
        <li>listdatas71</li>
        <li>listdatas72</li>
        <li>listdatas73</li>
        <li>listdatas74</li>
        <li>listdatas75</li>
        <li>listdatas76</li>
        <li>listdatas77</li>
        <li>listdatas78</li>
        <li>listdatas79</li>
        <li>listdatas80</li>
        <li>listdatas81</li>
        <li>listdatas82</li>
        <li>listdatas83</li>
        <li>listdatas84</li>
        <li>listdatas85</li>
        <li>listdatas86</li>
        <li>listdatas87</li>
        <li>listdatas88</li>
        <li>listdatas89</li>
        <li>listdatas90</li>
        <li>listdatas91</li>
        <li>listdatas92</li>
        <li>listdatas93</li>
        <li>listdatas94</li>
        <li>listdatas95</li>
        <li>listdatas96</li>
        <li>listdatas97</li>
        <li>listdatas98</li>
        <li>listdatas99</li>
        <li>listdatas100</li>
      </ul>
    </scroll>
  </div>
</template>
<script>
  import Scroll from 'components/common/scroll/Scroll'

  export default {
    name:'Profile',
    components:{
      Scroll
    }
  }
</script>

<style scoped>
  .content{
    height:300px;
    background-color:red;
    overflow:hidden ;
  }

</style>